// Do not modify this file, it will be autogenerated
// created on 21.04.2020 18:01:00

export const root = {
  dto: {
     $dtoType: {
        create: 'dto.$dtoType.create',
        read: 'dto.$dtoType.read',
        write: 'dto.$dtoType.write',
        delete: 'dto.$dtoType.delete',
        $dtoField: {
           create: 'dto.$dtoType.$dtoField.create',
           read: 'dto.$dtoType.$dtoField.read',
           write: 'dto.$dtoType.$dtoField.write'
        }
     },
     FileAttachment: {
        upload: 'dto.FileAttachment.upload',
        download: 'dto.FileAttachment.download'
     },
     Order: {
        read: 'dto.Order.read'
     }
  },
  scheduler: {
     open: 'scheduler.open',
     event: {
        leaf: 'scheduler.event.leaf'
     }
  }
};


export const list = [
  'dto.$dtoType.create',
  'dto.$dtoType.read',
  'dto.$dtoType.write',
  'dto.$dtoType.delete',
  'dto.$dtoType.$dtoField.create',
  'dto.$dtoType.$dtoField.read',
  'dto.$dtoType.$dtoField.write',
  'dto.FileAttachment.upload',
  'dto.FileAttachment.download',
  'dto.Order.read',
  'scheduler.open',
  'scheduler.event.leaf'
];

