// Do not modify this file, it will be autogenerated
// created on 26.03.2020 09:43:13

import { RootStoreSelectors } from "src/app/root-store/root-index"

export const root = {
	foo: {
		hossa: "foo.hossa",
		leaf: "foo.leaf",
		bar: {
			one: "foo.bar.one",
			two: "foo.bar.two"
		},
		baz: {
			three: "foo.baz.three",
			four: "foo.baz.four"
		},
		scheduler: {
			event: {
				leaf: "foo.scheduler.event.leaf"
			}
		}
	},
	dto: {
		$dtoType: {
			$dtoField: {
				create: "dto.$dtoType.$dtoField.create",
				read: "dto.$dtoType.$dtoField.read",
				write: "dto.$dtoType.$dtoField.write"
			}
		},
		FileAttachment: {
			upload: "dto.FileAttachment.upload",
			download: "dto.FileAttachment.download"
		}
	}
}

